// src/components/SideBar.tsx
import Link from "next/link";
import { Accordion, AccordionTab } from "primereact/accordion";
import { Card } from "primereact/card";

const SideBar = () => (
  <div className="container-side-bar">
    <Card title="SrfGroup">
      <p className="m-0">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed
        consequuntur error repudiandae numquam deserunt quisquam repellat libero
        asperiores earum nam nobis, culpa ratione quam perferendis esse,
        cupiditate neque quas!
      </p>
    </Card>
    <Accordion multiple>
      <AccordionTab header="Dashboard Mangment">
        <ul>
          <li className="py-4">
            <Link href="/dashboard">Dashboard</Link>
          </li>
          <li className="py-4">
            <Link href="/dashboard/logs">Logs</Link>
          </li>

          <li className="py-4">
            <Link href="/dashboard/organigramme">Organigramme</Link>
          </li>
        </ul>
      </AccordionTab>
      <AccordionTab header="User Mangment">
        <ul>
          <li className="py-4">
            <Link href="/user/list-users">List users</Link>
          </li>
          <li className="py-4">
            <Link href="/about">Add user</Link>
          </li>
        </ul>
      </AccordionTab>
      <AccordionTab header="Role Mangment">
        <ul>
          <li className="py-4">
            <Link href="/role/list-roles">List roles</Link>
          </li>
          <li className="py-4">
            <Link href="/role/add-role">Add Role</Link>
          </li>
          <li className="py-4">
            <Link href="/role/list-permissions">List permissions</Link>
          </li>
          <li className="py-4">
            <Link href="/role/add-permission">Add permission</Link>
          </li>
        </ul>
      </AccordionTab>
      <AccordionTab header="Offer Mangment">
        <ul>
          <li className="py-4">
            <Link href="/offer/list-offers">List offers</Link>
          </li>

          <li className="py-4">
            <Link href="/offer/list-advertising-offers">List advertisings</Link>
          </li>

          <li className="py-4">
            <Link href="/offer/statistics">Statistics offers</Link>
          </li>

          <li className="py-4">
            <Link href="/offer/description-add-offer/description-new-offer">
              Description new offer
            </Link>
          </li>
        </ul>
      </AccordionTab>

      <AccordionTab header="Home Mangment">
        <ul>
          <li className="py-4">
            <Link href="/home/top-slides-images">Top Slides Images</Link>
          </li>
          <li className="py-4">
            <Link href="/home/feature-home">Feature Home</Link>
          </li>
        </ul>
      </AccordionTab>

      <AccordionTab header="Support Mangment">
        <ul>
          <li className="py-4">
            <Link href="/contact-us">Contact us</Link>
          </li>
          <li className="py-4">
            <Link href="/about-us">About US</Link>
          </li>
          <li className="py-4">
            <Link href="/faq">FAQ</Link>
          </li>
          <li className="py-4">
            <Link href="/news-letter">NewsLetter</Link>
          </li>
          <li className="py-4">
            <Link href="/declaration">Declaration</Link>
          </li>
          <li className="py-4">
            <Link href="/cgu/list-cgu">CGU</Link>
          </li>
        </ul>
      </AccordionTab>

      <AccordionTab header="Category Mangment">
        <ul>
          <li className="py-4">
            <Link href="/category/list-categories">List categories</Link>
          </li>
          <li className="py-4">
            <Link href="/category/add-category">Add category</Link>
          </li>
        </ul>
      </AccordionTab>

      <AccordionTab header="Address Mangment">
        <ul>
          <li className="py-4">
            <Link href="/address/list-address">List address</Link>
          </li>
          <li>
            <Link href="/about">Add address</Link>
          </li>
        </ul>
      </AccordionTab>
    </Accordion>
  </div>
);

export default SideBar;

// src/app/shared/layouts/side-bar/side-bar.component.ts
import { Component, ViewEncapsulation} from '@angular/core';

@Component({
    selector: 'app-side-bar',
    templateUrl: './side-bar.component.html',
    styleUrls: ['./side-bar.component.scss'],
    encapsulation: ViewEncapsulation.None,
})
export class SideBarComponent{

}

<h4>SrfGroup</h4>
<div class="container-side-bar">
    <p-accordion [multiple]="true">
        <p-accordionTab header="Dashboard Mangment">
            <ul>
                <li className="py-4" routerLink="/private/dashboard/metrics">Dashboard</li>
                <li className="py-4" routerLink="/private/dashboard/logs">Logs</li>

                <li className="py-4" routerLink="/private/dashboard/organigramme">Organigramme</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="User Management">
            <ul>
                <li className="py-4" routerLink="/private/user/list">List Users</li>
                <li className="py-4" routerLink="/private/dashboard/logs">Logs</li>

                <li className="py-4" routerLink="/private/dashboard/organigramme">Organigramme</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="Role Management">
            <ul>
                <li className="py-4" routerLink="/private/role/list-role">List Roles</li>
                <li className="py-4" routerLink="/private/role/list-permissions">List Permissions</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="Offer Management">
            <ul>
                <li className="py-4" routerLink="/private/offer/list">List Offers</li>
                <li className="py-4" routerLink="/private/offer/description-add-new-offer">DescriptionAddNewOffer</li>
                <li className="py-4" routerLink="/private/dashboard/logs">Logs</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="Home Management">
            <ul>
                <li className="py-4" routerLink="/private/home/top-slides">List Top Slides</li>

                <li className="py-4" routerLink="/private/home/list-feature-slide">List Feature Slide</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="Support Management">
            <ul>
                <li className="py-4" routerLink="/private/support/list-contact-us">Contact Us</li>
                <li className="py-4" routerLink="/private/support/list-about-us">About Us</li>
                <li className="py-4" routerLink="/private/support/list-newsletter">NewsLetter</li>
                <li className="py-4" routerLink="/private/support/list-declaration">Declaration</li>
                <li className="py-4" routerLink="/private/support/list-faq">FAQ</li>
                <li className="py-4" routerLink="/private/support/list-cgu">CGU</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="Address Management">
            <ul>
                <li className="py-4" routerLink="/private/address/list">List address</li>
            </ul>
        </p-accordionTab>
        <p-accordionTab header="Category Management">
            <ul>
                <li className="py-4" routerLink="/private/category/list">List categories</li>
            </ul>
        </p-accordionTab>
    </p-accordion>
</div>
